import React from 'react';

/**
 * Power BI visual-type placeholder icons.
 * Minimal 48x48 glyphs — inherit color via CSS `color` (neutral tone) and
 * a single accent via the --ac CSS custom property, so light/dark theming
 * is just a color swap, not separate art. Scales via width/height (SVG
 * viewBox keeps proportions — safe to stretch the container without warping).
 */

export type PowerBiIconName =
  | "clusteredColumn" | "stackedColumn" | "100StackedColumn" | "clusteredBar" | "stackedBar" | "100StackedBar" | "line" | "area" | "stackedArea" | "waterfall" | "ribbon" | "scatter" | "lineAndStackedColumn" | "lineAndClusteredColumn" | "funnel" | "pie" | "donut" | "treemap" | "card" | "cardNew" | "multiRowCard" | "kPI" | "gauge" | "table" | "matrix" | "slicer" | "buttonSlicer" | "textSlicer" | "listSlicer" | "map" | "filledMap" | "azureMap" | "arcGISMap" | "keyInfluencers" | "decompositionTree" | "qandA" | "smartNarrative" | "goals" | "pythonVisual" | "rVisual" | "paginatedReport" | "textBox" | "shape" | "image" | "button" | "bookmarkNav" | "pageNav" | "powerApps" | "powerAutomate";

interface IconDef {
  label: string;
  inner: string;
}

const ICONS: Record<PowerBiIconName, IconDef> = {
  "clusteredColumn": { label: "Clustered Column", inner: "<rect x=\"12\" y=\"24\" width=\"5\" height=\"16\" rx=\"1.6\" fill=\"currentColor\" stroke=\"none\"/>\n            <rect x=\"20\" y=\"16\" width=\"5\" height=\"24\" rx=\"1.6\" fill=\"currentColor\" stroke=\"none\"/>\n            <rect x=\"28\" y=\"28\" width=\"5\" height=\"12\" rx=\"1.6\" fill=\"currentColor\" stroke=\"none\"/>\n            <rect x=\"36\" y=\"10\" width=\"5\" height=\"30\" rx=\"1.6\" stroke=\"none\" style=\"fill:var(--ac,#2f7de1)\"/>\n            <line x1=\"9\" y1=\"41.5\" x2=\"43\" y2=\"41.5\" opacity=\"0.28\"/>" },
  "stackedColumn": { label: "Stacked Column", inner: "<rect x=\"14\" y=\"27\" width=\"6\" height=\"13\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"14\" y=\"17\" width=\"6\" height=\"9\" rx=\"1.4\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <rect x=\"24\" y=\"23\" width=\"6\" height=\"17\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"24\" y=\"13\" width=\"6\" height=\"9\" rx=\"1.4\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <rect x=\"34\" y=\"30\" width=\"6\" height=\"10\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"34\" y=\"20\" width=\"6\" height=\"9\" rx=\"1.4\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <line x1=\"9\" y1=\"41.5\" x2=\"43\" y2=\"41.5\" opacity=\"0.28\"/>" },
  "100StackedColumn": { label: "100% Stacked Column", inner: "<rect x=\"15\" y=\"31\" width=\"6\" height=\"10\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"15\" y=\"20\" width=\"6\" height=\"10\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\" opacity=\".45\"/><rect x=\"15\" y=\"9\" width=\"6\" height=\"10\" rx=\"1.4\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <rect x=\"25\" y=\"33\" width=\"6\" height=\"8\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"25\" y=\"21\" width=\"6\" height=\"11\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\" opacity=\".45\"/><rect x=\"25\" y=\"9\" width=\"6\" height=\"11\" rx=\"1.4\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <rect x=\"35\" y=\"28\" width=\"6\" height=\"13\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"35\" y=\"19\" width=\"6\" height=\"8\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\" opacity=\".45\"/><rect x=\"35\" y=\"9\" width=\"6\" height=\"9\" rx=\"1.4\" stroke=\"none\" style=\"fill:var(--ac)\"/>" },
  "clusteredBar": { label: "Clustered Bar", inner: "<rect x=\"10\" y=\"12\" width=\"18\" height=\"5\" rx=\"1.6\" fill=\"currentColor\" stroke=\"none\"/>\n            <rect x=\"10\" y=\"20\" width=\"26\" height=\"5\" rx=\"1.6\" fill=\"currentColor\" stroke=\"none\"/>\n            <rect x=\"10\" y=\"28\" width=\"14\" height=\"5\" rx=\"1.6\" fill=\"currentColor\" stroke=\"none\"/>\n            <rect x=\"10\" y=\"36\" width=\"30\" height=\"5\" rx=\"1.6\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <line x1=\"9\" y1=\"9\" x2=\"9\" y2=\"43\" opacity=\"0.28\"/>" },
  "stackedBar": { label: "Stacked Bar", inner: "<rect x=\"10\" y=\"13\" width=\"16\" height=\"6\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"26\" y=\"13\" width=\"8\" height=\"6\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\" opacity=\".45\"/><rect x=\"34\" y=\"13\" width=\"6\" height=\"6\" rx=\"1.4\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <rect x=\"10\" y=\"21\" width=\"10\" height=\"6\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"20\" y=\"21\" width=\"8\" height=\"6\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\" opacity=\".45\"/><rect x=\"28\" y=\"21\" width=\"4\" height=\"6\" rx=\"1.4\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <rect x=\"10\" y=\"29\" width=\"14\" height=\"6\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"24\" y=\"29\" width=\"8\" height=\"6\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\" opacity=\".45\"/><rect x=\"32\" y=\"29\" width=\"4\" height=\"6\" rx=\"1.4\" stroke=\"none\" style=\"fill:var(--ac)\"/>" },
  "100StackedBar": { label: "100% Stacked Bar", inner: "<rect x=\"10\" y=\"14\" width=\"15\" height=\"6\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"25.5\" y=\"14\" width=\"9\" height=\"6\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\" opacity=\".45\"/><rect x=\"35\" y=\"14\" width=\"5\" height=\"6\" rx=\"1.4\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <rect x=\"10\" y=\"22\" width=\"11\" height=\"6\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"21.5\" y=\"22\" width=\"13\" height=\"6\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\" opacity=\".45\"/><rect x=\"35\" y=\"22\" width=\"5\" height=\"6\" rx=\"1.4\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <rect x=\"10\" y=\"30\" width=\"18\" height=\"6\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"28.5\" y=\"30\" width=\"6.5\" height=\"6\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\" opacity=\".45\"/><rect x=\"35.5\" y=\"30\" width=\"4.5\" height=\"6\" rx=\"1.4\" stroke=\"none\" style=\"fill:var(--ac)\"/>" },
  "line": { label: "Line", inner: "<path d=\"M10 33 L18 23 L26 28 L34 16 L41 22\" fill=\"none\"/>\n            <circle cx=\"41\" cy=\"22\" r=\"2.6\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <line x1=\"9\" y1=\"41.5\" x2=\"43\" y2=\"41.5\" opacity=\"0.28\"/>" },
  "area": { label: "Area", inner: "<path d=\"M10 30 L18 22 L26 26 L34 16 L41 20 L41 40 L10 40 Z\" stroke=\"none\" fill-opacity=\"0.18\" style=\"fill:var(--ac)\"/>\n            <path d=\"M10 30 L18 22 L26 26 L34 16 L41 20\" fill=\"none\"/>\n            <line x1=\"9\" y1=\"41.5\" x2=\"43\" y2=\"41.5\" opacity=\"0.28\"/>" },
  "stackedArea": { label: "Stacked Area", inner: "<path d=\"M10 26 L18 18 L26 22 L34 13 L41 18 L41 40 L10 40 Z\" stroke=\"none\" fill-opacity=\"0.2\" style=\"fill:var(--ac)\"/>\n            <path d=\"M10 32 L18 27 L26 30 L34 25 L41 28 L41 40 L10 40 Z\" fill=\"currentColor\" stroke=\"none\" opacity=\".4\"/>\n            <path d=\"M10 26 L18 18 L26 22 L34 13 L41 18\" fill=\"none\" style=\"stroke:var(--ac)\"/>\n            <path d=\"M10 32 L18 27 L26 30 L34 25 L41 28\" fill=\"none\"/>" },
  "waterfall": { label: "Waterfall", inner: "<rect x=\"11\" y=\"25\" width=\"6\" height=\"9\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\"/>\n            <rect x=\"20\" y=\"18\" width=\"6\" height=\"7\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\"/>\n            <rect x=\"29\" y=\"25\" width=\"6\" height=\"7\" rx=\"1.4\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <rect x=\"38\" y=\"14\" width=\"6\" height=\"11\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\"/>\n            <line x1=\"17\" y1=\"25\" x2=\"20\" y2=\"25\" opacity=\".3\"/><line x1=\"26\" y1=\"25\" x2=\"29\" y2=\"25\" opacity=\".3\"/><line x1=\"35\" y1=\"25\" x2=\"38\" y2=\"25\" opacity=\".3\"/>" },
  "ribbon": { label: "Ribbon", inner: "<path d=\"M16 28 C19 28 19 24 22 24 L22 40 L16 40 Z\" fill=\"currentColor\" stroke=\"none\" opacity=\".28\"/>\n            <path d=\"M28 24 C31 24 31 30 34 30 L34 40 L28 40 Z\" fill=\"currentColor\" stroke=\"none\" opacity=\".28\"/>\n            <path d=\"M16 18 C19 18 19 14 22 14 L22 24 C19 24 19 28 16 28 Z\" stroke=\"none\" style=\"fill:var(--ac)\" opacity=\".5\"/>\n            <path d=\"M28 14 C31 14 31 16 34 16 L34 30 C31 30 31 24 28 24 Z\" stroke=\"none\" style=\"fill:var(--ac)\" opacity=\".5\"/>\n            <rect x=\"10\" y=\"28\" width=\"6\" height=\"12\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"10\" y=\"18\" width=\"6\" height=\"10\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <rect x=\"22\" y=\"24\" width=\"6\" height=\"16\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"22\" y=\"14\" width=\"6\" height=\"10\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <rect x=\"34\" y=\"30\" width=\"6\" height=\"10\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"34\" y=\"16\" width=\"6\" height=\"14\" stroke=\"none\" style=\"fill:var(--ac)\"/>" },
  "scatter": { label: "Scatter", inner: "<circle cx=\"14\" cy=\"30\" r=\"2.6\" fill=\"currentColor\" stroke=\"none\"/>\n            <circle cx=\"20\" cy=\"20\" r=\"2.6\" fill=\"currentColor\" stroke=\"none\"/>\n            <circle cx=\"27\" cy=\"26\" r=\"2.6\" fill=\"currentColor\" stroke=\"none\"/>\n            <circle cx=\"31\" cy=\"14\" r=\"2.6\" fill=\"currentColor\" stroke=\"none\"/>\n            <circle cx=\"37\" cy=\"21\" r=\"2.6\" fill=\"currentColor\" stroke=\"none\"/>\n            <circle cx=\"24\" cy=\"33\" r=\"3.2\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <line x1=\"9\" y1=\"41.5\" x2=\"43\" y2=\"41.5\" opacity=\"0.28\"/><line x1=\"9\" y1=\"9\" x2=\"9\" y2=\"41.5\" opacity=\"0.28\"/>" },
  "lineAndStackedColumn": { label: "Line & Stacked Column", inner: "<rect x=\"12\" y=\"28\" width=\"6\" height=\"12\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"12\" y=\"20\" width=\"6\" height=\"7\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\" opacity=\".45\"/>\n            <rect x=\"22\" y=\"24\" width=\"6\" height=\"16\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"22\" y=\"16\" width=\"6\" height=\"7\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\" opacity=\".45\"/>\n            <rect x=\"32\" y=\"30\" width=\"6\" height=\"10\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"32\" y=\"22\" width=\"6\" height=\"7\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\" opacity=\".45\"/>\n            <path d=\"M15 15 L25 11 L35 17\" fill=\"none\" style=\"stroke:var(--ac)\"/>\n            <circle cx=\"25\" cy=\"11\" r=\"2\" stroke=\"none\" style=\"fill:var(--ac)\"/>" },
  "lineAndClusteredColumn": { label: "Line & Clustered Column", inner: "<rect x=\"12\" y=\"22\" width=\"4.5\" height=\"18\" rx=\"1.2\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"17.5\" y=\"26\" width=\"4.5\" height=\"14\" rx=\"1.2\" fill=\"currentColor\" stroke=\"none\" opacity=\".45\"/>\n            <rect x=\"27\" y=\"18\" width=\"4.5\" height=\"22\" rx=\"1.2\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"32.5\" y=\"24\" width=\"4.5\" height=\"16\" rx=\"1.2\" fill=\"currentColor\" stroke=\"none\" opacity=\".45\"/>\n            <path d=\"M14 20 L24 15 L34 12\" fill=\"none\" style=\"stroke:var(--ac)\"/>\n            <circle cx=\"24\" cy=\"15\" r=\"2\" stroke=\"none\" style=\"fill:var(--ac)\"/>" },
  "funnel": { label: "Funnel", inner: "<rect x=\"9\" y=\"11\" width=\"30\" height=\"6\" rx=\"2\" fill=\"currentColor\" stroke=\"none\"/>\n            <rect x=\"13\" y=\"20\" width=\"22\" height=\"6\" rx=\"2\" fill=\"currentColor\" stroke=\"none\"/>\n            <rect x=\"17\" y=\"29\" width=\"14\" height=\"6\" rx=\"2\" fill=\"currentColor\" stroke=\"none\"/>\n            <rect x=\"20\" y=\"37\" width=\"8\" height=\"5\" rx=\"2\" stroke=\"none\" style=\"fill:var(--ac)\"/>" },
  "pie": { label: "Pie", inner: "<circle cx=\"24\" cy=\"24\" r=\"14\" fill=\"none\"/>\n            <path d=\"M24 24 L24 10 A14 14 0 0 1 37.1 19 Z\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <line x1=\"24\" y1=\"24\" x2=\"24\" y2=\"10\"/>\n            <line x1=\"24\" y1=\"24\" x2=\"37.1\" y2=\"19\"/>" },
  "donut": { label: "Donut", inner: "<circle cx=\"24\" cy=\"24\" r=\"12\" fill=\"none\" style=\"stroke-width:6\" opacity=\".9\"/>\n            <circle cx=\"24\" cy=\"24\" r=\"12\" fill=\"none\" stroke-dasharray=\"24 100\" transform=\"rotate(-90 24 24)\" style=\"stroke:var(--ac);stroke-width:6\"/>" },
  "treemap": { label: "Treemap", inner: "<rect x=\"9\" y=\"9\" width=\"17\" height=\"17\" rx=\"1.6\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <rect x=\"28\" y=\"9\" width=\"11\" height=\"17\" rx=\"1.6\" fill=\"currentColor\" stroke=\"none\"/>\n            <rect x=\"9\" y=\"28\" width=\"10\" height=\"11\" rx=\"1.6\" fill=\"currentColor\" stroke=\"none\"/>\n            <rect x=\"21\" y=\"28\" width=\"18\" height=\"11\" rx=\"1.6\" fill=\"currentColor\" stroke=\"none\" opacity=\".55\"/>" },
  "card": { label: "Card", inner: "<rect x=\"12\" y=\"16\" width=\"14\" height=\"3\" rx=\"1.5\" fill=\"currentColor\" stroke=\"none\" opacity=\".5\"/>\n            <rect x=\"12\" y=\"23\" width=\"24\" height=\"8\" rx=\"2\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <rect x=\"12\" y=\"34\" width=\"18\" height=\"3\" rx=\"1.5\" fill=\"currentColor\" stroke=\"none\" opacity=\".35\"/>" },
  "cardNew": { label: "Card (new)", inner: "<rect x=\"12\" y=\"16\" width=\"14\" height=\"3\" rx=\"1.5\" fill=\"currentColor\" stroke=\"none\" opacity=\".5\"/>\n            <rect x=\"12\" y=\"23\" width=\"24\" height=\"8\" rx=\"2\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <rect x=\"12\" y=\"34\" width=\"18\" height=\"3\" rx=\"1.5\" fill=\"currentColor\" stroke=\"none\" opacity=\".35\"/>" },
  "multiRowCard": { label: "Multi-Row Card", inner: "<rect x=\"11\" y=\"11\" width=\"9\" height=\"2.5\" rx=\"1.25\" fill=\"currentColor\" stroke=\"none\" opacity=\".4\"/>\n            <rect x=\"11\" y=\"15\" width=\"20\" height=\"4\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\"/>\n            <line x1=\"11\" y1=\"24\" x2=\"37\" y2=\"24\" opacity=\".2\"/>\n            <rect x=\"11\" y=\"26.5\" width=\"9\" height=\"2.5\" rx=\"1.25\" fill=\"currentColor\" stroke=\"none\" opacity=\".4\"/>\n            <rect x=\"11\" y=\"30.5\" width=\"16\" height=\"4\" rx=\"1.4\" stroke=\"none\" style=\"fill:var(--ac)\"/>" },
  "kPI": { label: "KPI", inner: "<rect x=\"11\" y=\"13\" width=\"14\" height=\"3\" rx=\"1.5\" fill=\"currentColor\" stroke=\"none\" opacity=\".45\"/>\n            <line x1=\"11\" y1=\"22\" x2=\"37\" y2=\"22\" stroke-dasharray=\"3 3\" opacity=\".4\"/>\n            <path d=\"M11 33 L19 27 L26 30 L34 20\" fill=\"none\" style=\"stroke:var(--ac)\"/>\n            <circle cx=\"34\" cy=\"20\" r=\"2.6\" stroke=\"none\" style=\"fill:var(--ac)\"/>" },
  "gauge": { label: "Gauge", inner: "<path d=\"M11 33 A13 13 0 0 1 37 33\" fill=\"none\" opacity=\".3\" style=\"stroke-width:3.4\"/>\n            <path d=\"M11 33 A13 13 0 0 1 24.5 20.05\" fill=\"none\" style=\"stroke:var(--ac);stroke-width:3.4\"/>\n            <line x1=\"24\" y1=\"33\" x2=\"30\" y2=\"24\"/>\n            <circle cx=\"24\" cy=\"33\" r=\"2.4\" fill=\"currentColor\" stroke=\"none\"/>" },
  "table": { label: "Table", inner: "<rect x=\"9\" y=\"11\" width=\"30\" height=\"26\" rx=\"2.5\" fill=\"none\"/>\n            <rect x=\"9.6\" y=\"11.6\" width=\"28.8\" height=\"6\" stroke=\"none\" fill-opacity=\".2\" style=\"fill:var(--ac)\"/>\n            <line x1=\"9\" y1=\"24\" x2=\"39\" y2=\"24\" opacity=\".35\"/>\n            <line x1=\"9\" y1=\"30.5\" x2=\"39\" y2=\"30.5\" opacity=\".35\"/>\n            <line x1=\"19\" y1=\"17.6\" x2=\"19\" y2=\"37\" opacity=\".35\"/>\n            <line x1=\"29\" y1=\"17.6\" x2=\"29\" y2=\"37\" opacity=\".35\"/>" },
  "matrix": { label: "Matrix", inner: "<rect x=\"9\" y=\"11\" width=\"30\" height=\"26\" rx=\"2.5\" fill=\"none\"/>\n            <rect x=\"9.6\" y=\"11.6\" width=\"28.8\" height=\"6\" stroke=\"none\" fill-opacity=\".2\" style=\"fill:var(--ac)\"/>\n            <rect x=\"9.6\" y=\"17.6\" width=\"8\" height=\"18.8\" fill=\"currentColor\" stroke=\"none\" fill-opacity=\".14\"/>\n            <line x1=\"9\" y1=\"24\" x2=\"39\" y2=\"24\" opacity=\".35\"/>\n            <line x1=\"9\" y1=\"30.5\" x2=\"39\" y2=\"30.5\" opacity=\".35\"/>\n            <line x1=\"17.6\" y1=\"17.6\" x2=\"17.6\" y2=\"37\" opacity=\".35\"/>\n            <line x1=\"28\" y1=\"17.6\" x2=\"28\" y2=\"37\" opacity=\".35\"/>" },
  "slicer": { label: "Slicer", inner: "<rect x=\"11\" y=\"13\" width=\"6\" height=\"6\" rx=\"1.6\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <rect x=\"21\" y=\"14\" width=\"18\" height=\"4\" rx=\"2\" fill=\"currentColor\" stroke=\"none\" opacity=\".55\"/>\n            <rect x=\"11\" y=\"23\" width=\"6\" height=\"6\" rx=\"1.6\" fill=\"none\" opacity=\".7\"/>\n            <rect x=\"21\" y=\"24\" width=\"14\" height=\"4\" rx=\"2\" fill=\"currentColor\" stroke=\"none\" opacity=\".4\"/>\n            <rect x=\"11\" y=\"33\" width=\"6\" height=\"6\" rx=\"1.6\" fill=\"none\" opacity=\".7\"/>\n            <rect x=\"21\" y=\"34\" width=\"16\" height=\"4\" rx=\"2\" fill=\"currentColor\" stroke=\"none\" opacity=\".4\"/>" },
  "buttonSlicer": { label: "Button Slicer", inner: "<rect x=\"9\" y=\"13\" width=\"14\" height=\"9\" rx=\"2.5\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <rect x=\"25\" y=\"13\" width=\"14\" height=\"9\" rx=\"2.5\" fill=\"none\" opacity=\".7\"/>\n            <rect x=\"9\" y=\"26\" width=\"14\" height=\"9\" rx=\"2.5\" fill=\"none\" opacity=\".7\"/>\n            <rect x=\"25\" y=\"26\" width=\"14\" height=\"9\" rx=\"2.5\" fill=\"none\" opacity=\".7\"/>" },
  "textSlicer": { label: "Text Slicer", inner: "<rect x=\"9\" y=\"18\" width=\"30\" height=\"12\" rx=\"3\" fill=\"none\"/>\n            <circle cx=\"15\" cy=\"24\" r=\"3\" fill=\"none\" style=\"stroke:var(--ac)\"/>\n            <line x1=\"17.2\" y1=\"26.2\" x2=\"19.5\" y2=\"28.5\" style=\"stroke:var(--ac)\"/>\n            <rect x=\"23\" y=\"22.7\" width=\"12\" height=\"2.6\" rx=\"1.3\" fill=\"currentColor\" stroke=\"none\" opacity=\".35\"/>" },
  "listSlicer": { label: "List Slicer", inner: "<rect x=\"9\" y=\"12\" width=\"30\" height=\"8\" rx=\"2\" stroke=\"none\" fill-opacity=\".14\" style=\"fill:var(--ac)\"/>\n            <circle cx=\"14\" cy=\"16\" r=\"2\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <rect x=\"19\" y=\"14.5\" width=\"18\" height=\"3\" rx=\"1.5\" fill=\"currentColor\" stroke=\"none\" opacity=\".6\"/>\n            <circle cx=\"14\" cy=\"26\" r=\"2\" fill=\"currentColor\" stroke=\"none\" opacity=\".5\"/>\n            <rect x=\"19\" y=\"24.5\" width=\"14\" height=\"3\" rx=\"1.5\" fill=\"currentColor\" stroke=\"none\" opacity=\".45\"/>\n            <circle cx=\"14\" cy=\"36\" r=\"2\" fill=\"currentColor\" stroke=\"none\" opacity=\".5\"/>\n            <rect x=\"19\" y=\"34.5\" width=\"16\" height=\"3\" rx=\"1.5\" fill=\"currentColor\" stroke=\"none\" opacity=\".45\"/>" },
  "map": { label: "Map", inner: "<rect x=\"8\" y=\"11\" width=\"32\" height=\"25\" rx=\"2\" fill=\"none\"/>\n            <line x1=\"18\" y1=\"11\" x2=\"18\" y2=\"36\" stroke-dasharray=\"2.2 2.2\" opacity=\".35\"/>\n            <line x1=\"30\" y1=\"11\" x2=\"30\" y2=\"36\" stroke-dasharray=\"2.2 2.2\" opacity=\".35\"/>\n            <path d=\"M13 30 L21 24 L26 28 L33 23\" fill=\"none\" opacity=\".55\"/>\n            <circle cx=\"13\" cy=\"30\" r=\"1.8\" fill=\"currentColor\" stroke=\"none\" opacity=\".6\"/>\n            <path d=\"M33 23 C31 20 30 18 30 16.3 C30 14 31.3 12 33 12 C34.7 12 36 14 36 16.3 C36 18 35 20 33 23 Z\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <circle cx=\"33\" cy=\"16\" r=\"1.4\" fill=\"#fff\" stroke=\"none\"/>" },
  "filledMap": { label: "Filled Map", inner: "<rect x=\"8\" y=\"11\" width=\"32\" height=\"25\" rx=\"2\" fill=\"none\"/>\n            <line x1=\"18\" y1=\"11\" x2=\"18\" y2=\"36\" stroke-dasharray=\"2.2 2.2\" opacity=\".35\"/>\n            <line x1=\"30\" y1=\"11\" x2=\"30\" y2=\"36\" stroke-dasharray=\"2.2 2.2\" opacity=\".35\"/>\n            <path d=\"M13 30 L21 24 L26 28 L33 23\" fill=\"none\" opacity=\".55\"/>\n            <circle cx=\"13\" cy=\"30\" r=\"1.8\" fill=\"currentColor\" stroke=\"none\" opacity=\".6\"/>\n            <path d=\"M33 23 C31 20 30 18 30 16.3 C30 14 31.3 12 33 12 C34.7 12 36 14 36 16.3 C36 18 35 20 33 23 Z\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <circle cx=\"33\" cy=\"16\" r=\"1.4\" fill=\"#fff\" stroke=\"none\"/>" },
  "azureMap": { label: "Azure Map", inner: "<rect x=\"8\" y=\"11\" width=\"32\" height=\"25\" rx=\"2\" fill=\"none\"/>\n            <line x1=\"18\" y1=\"11\" x2=\"18\" y2=\"36\" stroke-dasharray=\"2.2 2.2\" opacity=\".35\"/>\n            <line x1=\"30\" y1=\"11\" x2=\"30\" y2=\"36\" stroke-dasharray=\"2.2 2.2\" opacity=\".35\"/>\n            <path d=\"M13 30 L21 24 L26 28 L33 23\" fill=\"none\" opacity=\".55\"/>\n            <circle cx=\"13\" cy=\"30\" r=\"1.8\" fill=\"currentColor\" stroke=\"none\" opacity=\".6\"/>\n            <path d=\"M33 23 C31 20 30 18 30 16.3 C30 14 31.3 12 33 12 C34.7 12 36 14 36 16.3 C36 18 35 20 33 23 Z\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <circle cx=\"33\" cy=\"16\" r=\"1.4\" fill=\"#fff\" stroke=\"none\"/>" },
  "arcGISMap": { label: "ArcGIS Map", inner: "<rect x=\"8\" y=\"11\" width=\"32\" height=\"25\" rx=\"2\" fill=\"none\"/>\n            <line x1=\"18\" y1=\"11\" x2=\"18\" y2=\"36\" stroke-dasharray=\"2.2 2.2\" opacity=\".35\"/>\n            <line x1=\"30\" y1=\"11\" x2=\"30\" y2=\"36\" stroke-dasharray=\"2.2 2.2\" opacity=\".35\"/>\n            <path d=\"M13 30 L21 24 L26 28 L33 23\" fill=\"none\" opacity=\".55\"/>\n            <circle cx=\"13\" cy=\"30\" r=\"1.8\" fill=\"currentColor\" stroke=\"none\" opacity=\".6\"/>\n            <path d=\"M33 23 C31 20 30 18 30 16.3 C30 14 31.3 12 33 12 C34.7 12 36 14 36 16.3 C36 18 35 20 33 23 Z\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <circle cx=\"33\" cy=\"16\" r=\"1.4\" fill=\"#fff\" stroke=\"none\"/>" },
  "keyInfluencers": { label: "Key Influencers", inner: "<circle cx=\"15\" cy=\"24\" r=\"7\" stroke=\"none\" fill-opacity=\".9\" style=\"fill:var(--ac)\"/>\n            <line x1=\"21.5\" y1=\"20\" x2=\"30\" y2=\"15\" opacity=\".5\"/>\n            <line x1=\"22\" y1=\"24\" x2=\"31\" y2=\"23\" opacity=\".5\"/>\n            <line x1=\"21.5\" y1=\"28\" x2=\"31\" y2=\"31\" opacity=\".5\"/>\n            <circle cx=\"33\" cy=\"14\" r=\"3.4\" fill=\"currentColor\" stroke=\"none\"/>\n            <circle cx=\"34\" cy=\"23\" r=\"2.8\" fill=\"currentColor\" stroke=\"none\"/>\n            <circle cx=\"34\" cy=\"32\" r=\"3.2\" fill=\"currentColor\" stroke=\"none\"/>" },
  "decompositionTree": { label: "Decomposition Tree", inner: "<rect x=\"7\" y=\"20\" width=\"9\" height=\"8\" rx=\"2\" fill=\"currentColor\" stroke=\"none\"/>\n            <path d=\"M16 24 C20 24 20 15 24 15\" fill=\"none\" opacity=\".45\"/>\n            <path d=\"M16 24 C20 24 20 33 24 33\" fill=\"none\" opacity=\".45\"/>\n            <rect x=\"24\" y=\"11\" width=\"9\" height=\"8\" rx=\"2\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <rect x=\"24\" y=\"29\" width=\"9\" height=\"8\" rx=\"2\" fill=\"currentColor\" stroke=\"none\"/>\n            <path d=\"M33 15 L40 15\" fill=\"none\" opacity=\".45\"/>\n            <rect x=\"40\" y=\"11\" width=\"4\" height=\"8\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\" opacity=\".5\"/>" },
  "qandA": { label: "Q&A", inner: "<path d=\"M11 14 H37 A3 3 0 0 1 40 17 V27 A3 3 0 0 1 37 30 H22 L16 35 V30 H11 A3 3 0 0 1 8 27 V17 A3 3 0 0 1 11 14 Z\" fill=\"none\"/>\n            <text x=\"24\" y=\"27.5\" text-anchor=\"middle\" stroke=\"none\" font-size=\"14\" font-weight=\"700\" font-family=\"Segoe UI,system-ui\" style=\"fill:var(--ac)\">?</text>" },
  "smartNarrative": { label: "Smart Narrative", inner: "<rect x=\"10\" y=\"15\" width=\"20\" height=\"3\" rx=\"1.5\" fill=\"currentColor\" stroke=\"none\" opacity=\".55\"/>\n            <rect x=\"10\" y=\"21\" width=\"26\" height=\"3\" rx=\"1.5\" fill=\"currentColor\" stroke=\"none\" opacity=\".55\"/>\n            <rect x=\"10\" y=\"27\" width=\"23\" height=\"3\" rx=\"1.5\" fill=\"currentColor\" stroke=\"none\" opacity=\".55\"/>\n            <rect x=\"10\" y=\"33\" width=\"14\" height=\"3\" rx=\"1.5\" fill=\"currentColor\" stroke=\"none\" opacity=\".55\"/>\n            <path d=\"M35 9 L36.4 13.6 L41 15 L36.4 16.4 L35 21 L33.6 16.4 L29 15 L33.6 13.6 Z\" stroke=\"none\" style=\"fill:var(--ac)\"/>" },
  "goals": { label: "Goals", inner: "<circle cx=\"13\" cy=\"16\" r=\"2.4\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <rect x=\"19\" y=\"14\" width=\"20\" height=\"4\" rx=\"2\" fill=\"currentColor\" stroke=\"none\" opacity=\".18\"/>\n            <rect x=\"19\" y=\"14\" width=\"13\" height=\"4\" rx=\"2\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <circle cx=\"13\" cy=\"26\" r=\"2.4\" fill=\"currentColor\" stroke=\"none\" opacity=\".5\"/>\n            <rect x=\"19\" y=\"24\" width=\"20\" height=\"4\" rx=\"2\" fill=\"currentColor\" stroke=\"none\" opacity=\".18\"/>\n            <rect x=\"19\" y=\"24\" width=\"8\" height=\"4\" rx=\"2\" fill=\"currentColor\" stroke=\"none\"/>\n            <circle cx=\"13\" cy=\"36\" r=\"2.4\" fill=\"currentColor\" stroke=\"none\" opacity=\".5\"/>\n            <rect x=\"19\" y=\"34\" width=\"20\" height=\"4\" rx=\"2\" fill=\"currentColor\" stroke=\"none\" opacity=\".18\"/>\n            <rect x=\"19\" y=\"34\" width=\"16\" height=\"4\" rx=\"2\" fill=\"currentColor\" stroke=\"none\"/>" },
  "pythonVisual": { label: "Python Visual", inner: "<rect x=\"10\" y=\"11\" width=\"28\" height=\"26\" rx=\"4\" fill=\"none\"/>\n            <text x=\"24\" y=\"30\" text-anchor=\"middle\" stroke=\"none\" font-size=\"15\" font-weight=\"700\" font-family=\"Segoe UI,system-ui\" style=\"fill:var(--ac)\">Py</text>" },
  "rVisual": { label: "R Visual", inner: "<rect x=\"12\" y=\"11\" width=\"24\" height=\"26\" rx=\"4\" fill=\"none\"/>\n            <text x=\"24\" y=\"31\" text-anchor=\"middle\" stroke=\"none\" font-size=\"19\" font-weight=\"700\" font-family=\"Segoe UI,system-ui\" style=\"fill:var(--ac)\">R</text>" },
  "paginatedReport": { label: "Paginated Report", inner: "<path d=\"M14 9 H30 L34 13 V39 H14 Z\" fill=\"none\"/>\n            <path d=\"M30 9 V13 H34\" fill=\"none\" style=\"stroke:var(--ac)\"/>\n            <line x1=\"18\" y1=\"19\" x2=\"30\" y2=\"19\" opacity=\".5\"/>\n            <line x1=\"18\" y1=\"24\" x2=\"30\" y2=\"24\" opacity=\".5\"/>\n            <line x1=\"18\" y1=\"29\" x2=\"26\" y2=\"29\" opacity=\".5\"/>" },
  "textBox": { label: "Text Box", inner: "<rect x=\"11\" y=\"15\" width=\"26\" height=\"3\" rx=\"1.5\" fill=\"currentColor\" stroke=\"none\" opacity=\".55\"/>\n            <rect x=\"11\" y=\"21\" width=\"26\" height=\"3\" rx=\"1.5\" fill=\"currentColor\" stroke=\"none\" opacity=\".55\"/>\n            <rect x=\"11\" y=\"27\" width=\"26\" height=\"3\" rx=\"1.5\" fill=\"currentColor\" stroke=\"none\" opacity=\".55\"/>\n            <rect x=\"11\" y=\"33\" width=\"16\" height=\"3\" rx=\"1.5\" fill=\"currentColor\" stroke=\"none\" opacity=\".55\"/>" },
  "shape": { label: "Shape", inner: "<rect x=\"10\" y=\"15\" width=\"17\" height=\"17\" rx=\"3\" fill=\"none\"/>\n            <circle cx=\"31\" cy=\"28\" r=\"8\" fill=\"none\" style=\"stroke:var(--ac)\"/>" },
  "image": { label: "Image", inner: "<rect x=\"9\" y=\"12\" width=\"30\" height=\"24\" rx=\"3\" fill=\"none\"/>\n            <circle cx=\"17\" cy=\"19\" r=\"2.6\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <path d=\"M11 32 L18 24 L23 29 L30 20 L37 32\" fill=\"none\"/>" },
  "button": { label: "Button", inner: "<rect x=\"9\" y=\"15\" width=\"30\" height=\"14\" rx=\"5\" fill=\"none\" style=\"stroke:var(--ac)\"/>\n            <path d=\"M22 18 L22 26.5 L24.2 24.5 L26 28 L27.6 27.3 L25.6 23.7 L28.5 23.3 Z\" fill=\"currentColor\" stroke=\"none\"/>" },
  "bookmarkNav": { label: "Bookmark Nav", inner: "<path d=\"M12 12 H18 V25 L15 22 L12 25 Z\" stroke=\"none\" style=\"fill:var(--ac)\"/>\n            <path d=\"M21 12 H27 V25 L24 22 L21 25 Z\" fill=\"none\"/>\n            <path d=\"M30 12 H36 V25 L33 22 L30 25 Z\" fill=\"none\"/>\n            <circle cx=\"15\" cy=\"33\" r=\"1.7\" fill=\"currentColor\" stroke=\"none\" opacity=\".5\"/>\n            <circle cx=\"24\" cy=\"33\" r=\"1.7\" fill=\"currentColor\" stroke=\"none\" opacity=\".5\"/>\n            <circle cx=\"33\" cy=\"33\" r=\"1.7\" fill=\"currentColor\" stroke=\"none\" opacity=\".5\"/>" },
  "pageNav": { label: "Page Nav", inner: "<path d=\"M12 24 L8 24 M8 24 L10.7 21.2 M8 24 L10.7 26.8\" fill=\"none\"/>\n            <path d=\"M39 24 L43 24 M43 24 L40.3 21.2 M43 24 L40.3 26.8\" fill=\"none\"/>\n            <rect x=\"14\" y=\"19\" width=\"10\" height=\"10\" rx=\"1.4\" fill=\"currentColor\" stroke=\"none\" opacity=\".4\"/>\n            <rect x=\"26\" y=\"17.5\" width=\"11\" height=\"13\" rx=\"1.4\" stroke=\"none\" style=\"fill:var(--ac)\"/>" },
  "powerApps": { label: "Power Apps", inner: "<rect x=\"7\" y=\"9\" width=\"34\" height=\"30\" rx=\"4\" fill=\"none\"/>\n            <text x=\"24\" y=\"22\" text-anchor=\"middle\" stroke=\"none\" font-size=\"9\" font-weight=\"700\" font-family=\"Segoe UI,system-ui\" fill=\"currentColor\" opacity=\".55\">Power</text>\n            <text x=\"24\" y=\"33\" text-anchor=\"middle\" stroke=\"none\" font-size=\"11\" font-weight=\"700\" font-family=\"Segoe UI,system-ui\" style=\"fill:var(--ac)\">App</text>" },
  "powerAutomate": { label: "Power Automate", inner: "<rect x=\"7\" y=\"9\" width=\"34\" height=\"30\" rx=\"4\" fill=\"none\"/>\n            <text x=\"24\" y=\"22\" text-anchor=\"middle\" stroke=\"none\" font-size=\"9\" font-weight=\"700\" font-family=\"Segoe UI,system-ui\" fill=\"currentColor\" opacity=\".55\">Power</text>\n            <text x=\"24\" y=\"33\" text-anchor=\"middle\" stroke=\"none\" font-size=\"5.6\" font-weight=\"700\" font-family=\"Segoe UI,system-ui\" style=\"fill:var(--ac)\">Automate</text>" },
};

export const POWER_BI_ICON_NAMES = Object.keys(ICONS) as PowerBiIconName[];

export interface PowerBiIconProps extends Omit<React.SVGAttributes<SVGSVGElement>, 'name'> {
  /** Which visual-type glyph to render */
  name: PowerBiIconName;
  /** Icon box size (width & height), px or any CSS length. Default 24. */
  size?: number | string;
  /** Neutral tone. Defaults to inherited `color` (currentColor) — leave unset to follow your theme. */
  color?: string;
  /** Accent tone used for the highlighted series/segment. Default '#2f7de1'. */
  accentColor?: string;
  /** Line weight for stroke-based details. Default 2.4. */
  strokeWidth?: number;
}

export function PowerBiIcon({
  name,
  size = 24,
  color,
  accentColor = '#2f7de1',
  strokeWidth = 2.4,
  style,
  ...rest
}: PowerBiIconProps) {
  const def = ICONS[name];
  if (!def) return null;
  return (
    <svg
      viewBox="0 0 48 48"
      width={size}
      height={size}
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-label={def.label}
      role="img"
      data-icon-name={name}
      style={{
        overflow: 'visible',
        color,
        strokeWidth,
        '--ac': accentColor,
        ...style,
      } as React.CSSProperties}
      dangerouslySetInnerHTML={{ __html: def.inner }}
      {...rest}
    />
  );
}

export default PowerBiIcon;
